name: Issue
description: Raise an issue about anything
body:
  - type: dropdown
    id: game_version
    attributes:
      label: "Game Version"
      description: "Which game version is this issue for?"
      options:
        - The War Within
        - Cataclysm Classic
        - Classic Era (including Hardcore and Season of Discovery)
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: "Issue"
      description: "What is your issue?"
    validations:
      required: true
      required: true
