name: Bug report
description: Report an issue with the game
title: "[BUG] - "
labels: ["bug"]
body:
  - type: dropdown
    id: game_version
    attributes:
      label: "Game Version"
      description: "Select the version of the game you are reporting this issue about."
      options:
        - The War Within
        - Cataclysm Classic
        - Classic Era (including Hardcore and Season of Discovery)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Issue Description"
      description: "A clear and concise description of what the issue is."
    validations:
      required: true
